"""Dark theme definitions for Agent Chronicle TUI.

Each theme is inspired by a popular terminal/editor color scheme.
All themes use transparent backgrounds so the terminal wallpaper shows through.
Themes are registered with Textual's Theme API and can be switched
at runtime with the 't' key or via --theme CLI flag.
"""

from textual.theme import Theme

# All themes use "transparent" for background so the terminal bg shows through.
# Surface/panel colors use low-alpha hex to blend with the terminal background.

THEMES: dict[str, Theme] = {
    "catppuccin-mocha": Theme(
        name="catppuccin-mocha",
        primary="#a6e3a1",
        secondary="#89b4fa",
        error="#f38ba8",
        success="#a6e3a1",
        accent="#cba6f7",
        foreground="#cdd6f4",
        background="transparent",
        surface="#313244",
        panel="#181825",
        dark=True,
        variables={
            "overlay": "#45475a",
            "subtext": "#a6adc8",
            "muted": "#6c7086",
            "odd-row": "#232336",
            "cursor-bg": "#45475a",
            "focus-cursor": "#585b70",
            "border-color": "#45475a",
            "header-bg": "#181825",
        },
    ),
    "dracula": Theme(
        name="dracula",
        primary="#50fa7b",
        secondary="#bd93f9",
        error="#ff5555",
        success="#50fa7b",
        accent="#ff79c6",
        foreground="#f8f8f2",
        background="transparent",
        surface="#44475a",
        panel="#21222c",
        dark=True,
        variables={
            "overlay": "#6272a4",
            "subtext": "#bfbfbf",
            "muted": "#6272a4",
            "odd-row": "#2d303d",
            "cursor-bg": "#44475a",
            "focus-cursor": "#6272a4",
            "border-color": "#6272a4",
            "header-bg": "#21222c",
        },
    ),
    "nord": Theme(
        name="nord",
        primary="#88c0d0",
        secondary="#81a1c1",
        error="#bf616a",
        success="#a3be8c",
        accent="#b48ead",
        foreground="#eceff4",
        background="transparent",
        surface="#3b4252",
        panel="#272c36",
        dark=True,
        variables={
            "overlay": "#4c566a",
            "subtext": "#d8dee9",
            "muted": "#4c566a",
            "odd-row": "#333947",
            "cursor-bg": "#434c5e",
            "focus-cursor": "#4c566a",
            "border-color": "#4c566a",
            "header-bg": "#272c36",
        },
    ),
    "gruvbox-dark": Theme(
        name="gruvbox-dark",
        primary="#b8bb26",
        secondary="#83a598",
        error="#fb4934",
        success="#b8bb26",
        accent="#d3869b",
        foreground="#ebdbb2",
        background="transparent",
        surface="#3c3836",
        panel="#1d2021",
        dark=True,
        variables={
            "overlay": "#504945",
            "subtext": "#bdae93",
            "muted": "#665c54",
            "odd-row": "#2e2c2a",
            "cursor-bg": "#504945",
            "focus-cursor": "#665c54",
            "border-color": "#504945",
            "header-bg": "#1d2021",
        },
    ),
    "tokyo-night": Theme(
        name="tokyo-night",
        primary="#7aa2f7",
        secondary="#bb9af7",
        error="#f7768e",
        success="#9ece6a",
        accent="#e0af68",
        foreground="#c0caf5",
        background="transparent",
        surface="#24283b",
        panel="#16161e",
        dark=True,
        variables={
            "overlay": "#414868",
            "subtext": "#a9b1d6",
            "muted": "#565f89",
            "odd-row": "#1f2030",
            "cursor-bg": "#33467c",
            "focus-cursor": "#414868",
            "border-color": "#414868",
            "header-bg": "#16161e",
        },
    ),
    "one-dark": Theme(
        name="one-dark",
        primary="#98c379",
        secondary="#61afef",
        error="#e06c75",
        success="#98c379",
        accent="#c678dd",
        foreground="#abb2bf",
        background="transparent",
        surface="#2c313c",
        panel="#21252b",
        dark=True,
        variables={
            "overlay": "#3e4451",
            "subtext": "#828997",
            "muted": "#5c6370",
            "odd-row": "#2a2f38",
            "cursor-bg": "#3e4451",
            "focus-cursor": "#4b5263",
            "border-color": "#3e4451",
            "header-bg": "#21252b",
        },
    ),
    "solarized-dark": Theme(
        name="solarized-dark",
        primary="#859900",
        secondary="#268bd2",
        error="#dc322f",
        success="#859900",
        accent="#6c71c4",
        foreground="#839496",
        background="transparent",
        surface="#073642",
        panel="#00212b",
        dark=True,
        variables={
            "overlay": "#586e75",
            "subtext": "#93a1a1",
            "muted": "#586e75",
            "odd-row": "#003340",
            "cursor-bg": "#073642",
            "focus-cursor": "#586e75",
            "border-color": "#586e75",
            "header-bg": "#00212b",
        },
    ),
    "kanagawa": Theme(
        name="kanagawa",
        primary="#98bb6c",
        secondary="#7e9cd8",
        error="#e82424",
        success="#98bb6c",
        accent="#957fb8",
        foreground="#dcd7ba",
        background="transparent",
        surface="#2a2a37",
        panel="#16161d",
        dark=True,
        variables={
            "overlay": "#363646",
            "subtext": "#c8c093",
            "muted": "#54546d",
            "odd-row": "#252530",
            "cursor-bg": "#363646",
            "focus-cursor": "#54546d",
            "border-color": "#363646",
            "header-bg": "#16161d",
        },
    ),
    "rose-pine": Theme(
        name="rose-pine",
        primary="#31748f",
        secondary="#c4a7e7",
        error="#eb6f92",
        success="#31748f",
        accent="#f6c177",
        foreground="#e0def4",
        background="transparent",
        surface="#26233a",
        panel="#1f1d2e",
        dark=True,
        variables={
            "overlay": "#403d52",
            "subtext": "#908caa",
            "muted": "#6e6a86",
            "odd-row": "#1e1c2f",
            "cursor-bg": "#403d52",
            "focus-cursor": "#524f67",
            "border-color": "#403d52",
            "header-bg": "#1f1d2e",
        },
    ),
    "everforest-dark": Theme(
        name="everforest-dark",
        primary="#a7c080",
        secondary="#7fbbb3",
        error="#e67e80",
        success="#a7c080",
        accent="#d699b6",
        foreground="#d3c6aa",
        background="transparent",
        surface="#343f44",
        panel="#272e33",
        dark=True,
        variables={
            "overlay": "#475258",
            "subtext": "#9da9a0",
            "muted": "#7a8478",
            "odd-row": "#313b40",
            "cursor-bg": "#475258",
            "focus-cursor": "#56635d",
            "border-color": "#475258",
            "header-bg": "#272e33",
        },
    ),
    "monokai": Theme(
        name="monokai",
        primary="#a6e22e",
        secondary="#66d9ef",
        error="#f92672",
        success="#a6e22e",
        accent="#fd971f",
        foreground="#f8f8f2",
        background="transparent",
        surface="#3e3d32",
        panel="#1e1f1c",
        dark=True,
        variables={
            "overlay": "#49483e",
            "subtext": "#a59f85",
            "muted": "#75715e",
            "odd-row": "#2d2e2a",
            "cursor-bg": "#49483e",
            "focus-cursor": "#75715e",
            "border-color": "#49483e",
            "header-bg": "#1e1f1c",
        },
    ),
    "molokai": Theme(
        name="molokai",
        primary="#a6e22e",
        secondary="#66d9ef",
        error="#f92672",
        success="#a6e22e",
        accent="#ae81ff",
        foreground="#f8f8f2",
        background="transparent",
        surface="#383830",
        panel="#1b1d1e",
        dark=True,
        variables={
            "overlay": "#465457",
            "subtext": "#808080",
            "muted": "#556270",
            "odd-row": "#2d2e2a",
            "cursor-bg": "#465457",
            "focus-cursor": "#556270",
            "border-color": "#465457",
            "header-bg": "#1b1d1e",
        },
    ),
}

DEFAULT_THEME = "catppuccin-mocha"
THEME_NAMES = list(THEMES.keys())
